wiki:
  # TODO ignoreFiles는 리스트를 사용할 수 있도록 변경하기.
  ignoreFiles: .DS_Store|_attachements|.git|.gitignore
  defaultWorkingDirectory: ${user.dir}/wiki

spring:
  profiles.active: dev

---
spring:
  profiles: dev

wiki:
  gitUrl: https://github.com/devsejong/TIL.git

---
spring:
  profiles: production

wiki:
  gitUrl: NeedOverride

server.port: 80
